/*----- PROTECTED REGION ID(SimulatorStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        SimulatorStateMachine.cpp
//
// description : C++ source for the «name» and its alowed
//               methods for commands and attributes
//
// project :     simulator generator.
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// SVN only:
// $HeadURL:  $
//
// CVS only:
// $Source:  $
// $Log:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================



#include <Simulator.h>
#include <SimulatorClass.h>

/*----- PROTECTED REGION END -----*/	//	Simulator::SimulatorStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================
//  ON      |  
//  FAULT   |  


namespace Simulator_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : Simulator::is_Amplitude_allowed()
 *	Description : Execution allowed for Amplitude attribute
 */
//--------------------------------------------------------
bool Simulator::is_Amplitude_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Amplitude attribute in read access.
	/*----- PROTECTED REGION ID(Simulator::AmplitudeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Simulator::AmplitudeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Simulator::is_smsstring_allowed()
 *	Description : Execution allowed for smsstring attribute
 */
//--------------------------------------------------------
bool Simulator::is_smsstring_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for smsstring attribute in read access.
	/*----- PROTECTED REGION ID(Simulator::smsstringStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Simulator::smsstringStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : Simulator::is_UpdateAttributes_allowed()
 *	Description : Execution allowed for UpdateAttributes attribute
 */
//--------------------------------------------------------
bool Simulator::is_UpdateAttributes_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for UpdateAttributes command.
	/*----- PROTECTED REGION ID(Simulator::UpdateAttributesStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Simulator::UpdateAttributesStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(Simulator::SimulatorStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	Simulator::SimulatorStateAllowed.AdditionalMethods

}	//	End of namespace
